spring:
  datasource:
    #  驱动
    driver-class-name: org.h2.Driver
    # h2 内存数据库 内存模式连接配置 库名: db
    url: jdbc:h2:mem:db
    # 初始化数据表 DDL
    schema: classpath:sql/init.sql
    # 初始化数据 DML
    data: classpath:sql/data.sql
  h2:
    # 开启 console 访问，默认false
    console:
      enabled: true
      settings:
        # 开启h2 console 跟踪方便调试，默认 false
        trace: true
        # 允许 console 远程访问，默认false
        web-allow-others: true
      # h2 访问路径上下文
      path: /h2-console
# 日志
logging:
  level:
    cn:
      felord: debug